//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdminProduct()
        {
            this.BatDatas = new HashSet<BatData>();
            this.BatRegs = new HashSet<BatReg>();
        }
    
        public int Id { get; set; }
        public string P_Name { get; set; }
        public string Category { get; set; }
        public Nullable<int> Price { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public string Date { get; set; }
        public string EndDate { get; set; }
        public string DeliveryDate { get; set; }
        public string D_EndDate { get; set; }
        public string Shipping { get; set; }
        public string Image { get; set; }
        public Nullable<int> CustId { get; set; }
    
        public virtual Registration Registration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatData> BatDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatReg> BatRegs { get; set; }
    }
}
