//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BatData()
        {
            this.Order_01 = new HashSet<Order_01>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Price { get; set; }
        public string Date { get; set; }
        public Nullable<int> CustID { get; set; }
        public Nullable<int> ProId { get; set; }
    
        public virtual Registration Registration { get; set; }
        public virtual CustProduct CustProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_01> Order_01 { get; set; }
    }
}
