//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatReg
    {
        public int Id { get; set; }
        public Nullable<int> CustId { get; set; }
        public Nullable<int> proid { get; set; }
    
        public virtual AdminProduct AdminProduct { get; set; }
        public virtual Registration Registration { get; set; }
        public virtual CustProduct CustProduct { get; set; }
    }
}
