//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auction.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AuctionDataEntities1 : DbContext
    {
        public AuctionDataEntities1()
            : base("name=AuctionDataEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BatData> BatDatas { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CustProduct> CustProducts { get; set; }
        public virtual DbSet<ProName> ProNames { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<Order_01> Order_01 { get; set; }
    }
}
