//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> U_id { get; set; }
        public Nullable<int> Bid_id { get; set; }
        public Nullable<int> Pro_id { get; set; }
    
        public virtual BatData BatData { get; set; }
        public virtual CustProduct CustProduct { get; set; }
        public virtual Registration Registration { get; set; }
    }
}
